return {
    pacifist = function(cutscene, event)
        Game.world.music:stop()
        Game.fader:fadeIn()
        local kris = cutscene:getCharacter("kris")
        local susie = cutscene:getCharacter("susie")
        local ralsei = cutscene:getCharacter("ralsei")
        local wilter = cutscene:getCharacter("wilter")
            cutscene:detachFollowers()
            wilter:setSprite("death/dying1")
            cutscene:walkTo("kris", "kris1",0.1, "up")
            cutscene:walkTo("susie", "sus1",0.1, "up")
            cutscene:walkTo("ralsei", "ral1",0.1, "up")
            cutscene:fadeOut(0)
            cutscene:wait(5)
            cutscene:fadeIn(3)
            cutscene:wait(1)
            Game.world.music:play("wilter_pacifist")
            cutscene:setSpeaker(wilter)
            cutscene:text("* .[wait:5].[wait:5].")
            cutscene:text("* Heh[wait:5].[wait:5].")
            cutscene:text("* I guess I underestimated you,[wait:5] Kris.")
            cutscene:text("* You.[wait:5].[wait:5].")
            cutscene:text("* You're a lot stronger than I thought.")
            cutscene:text("* With that kind of power.")
            cutscene:text("* You could change the world.")
            cutscene:text("* But.")
            cutscene:text("* Why.[wait:5].[wait:5]?")
            wilter:setSprite("death/dying2")
            cutscene:text("* Why did you spare me?")
            cutscene:text("* I.[wait:5].[wait:10] I tried to kill you!")
            cutscene:text("* I don't understand.[wait:5].[wait:5].")
            cutscene:text("* Why would anyone.[wait:5].[wait:5]. ")
            wilter:setSprite("death/dying5")
            cutscene:text("* Let me live?!")
            cutscene:setSpeaker(susie)
            wilter:setSprite("death/dying2")
            cutscene:text("* Listen man.", "annoyed")
            cutscene:text("* Even though I really don't like you.", "neutral_side")
            cutscene:text("* You don't deserve to die.", "shy_down")
            cutscene:setSpeaker(ralsei)
            cutscene:text("* Sir,[wait:5] I understand you're hurting.", "frown")
            cutscene:text("* We've all made mistakes before.", "disappointed")
            cutscene:text("* But we have a chance to grow and change!", "pleased")
            cutscene:text("* To become better!", "smile")
            cutscene:setSpeaker(wilter)
            cutscene:text("* I wish that was the case,[wait:5] Ralsei.")
            cutscene:text("* But people like me.[wait:5].[wait:5].[wait:10] Don't get second chances.")
            cutscene:text("* We never get anything.")
            cutscene:text("* In the end,[wait:5] It all crumbles to dust.")
            cutscene:text("* Like nothing mattered.")
            cutscene:text("* But you.[wait:5].[wait:5].")
            cutscene:text("* Maybe.[wait:5].[wait:5].[wait:10] You can still save yourself.")
            cutscene:text("* Here,[wait:5] take this...")
            cutscene:walkTo("kris", "kris2", 1.5)
            cutscene:wait(2)
            cutscene:setSpeaker(default)
            Assets.stopAndPlaySound("item")
            wilter:setSprite("death/dying3")
            Game.inventory:tryGiveItem("bloombowtie")
            Assets.stopAndPlaySound("item")
            cutscene:text("* (You got BloomBowtie.)")
            Game.inventory:tryGiveItem("shadowcrystal")
            Assets.stopAndPlaySound("item")
            cutscene:text("* (You got ShadowCrystal.)")
            cutscene:walkTo("kris", "kris3", 0.5, "up")
            cutscene:wait(2)
            cutscene:setSpeaker(wilter)
            cutscene:text("[shake:1] * Now go on.[wait:5].[wait:5].")
            wilter:setSprite("death/dying4")
            cutscene:text("[shake:1] * I'll be...[wait:10] I'll be okay.")
            cutscene:walkTo("kris", "kris4", 0.8, "up")
            cutscene:wait(0.8)
            kris:setSprite("hug_right_2")
            wilter:setSprite("death/dying3")
            cutscene:wait(0.2)
            kris:setSprite("hug_right_3")
            cutscene:wait(1)
            wilter:setSprite("death/dying4")
            cutscene:text("[shake:2] * T[wait:5]h[wait:5]a[wait:5]n[wait:5]k [wait:5]y[wait:5]o[wait:5]u[wait:5].[wait:5].[wait:5].")
            cutscene:fadeOut(1)
            Game.world.music:fade(0, 1)
            cutscene:wait(1.5)
            wilter:remove()
            Assets.stopAndPlaySound("deathnoise")
            cutscene:wait(4)
            cutscene:fadeIn(3)
            kris:resetSprite()
            cutscene:attachFollowers()
            cutscene:attachCamera()
            cutscene:alignFollowers()
            
    end,

    endingcheck = function(cutscene, event)
        local kris = cutscene:getCharacter("kris")
        local kill = Game:getFlag("wilter_killed")
        local spare = Game:getFlag("wilter_spared")
        if spare then
            cutscene:loadMap("pacifist_room", "spawn")
            cutscene:gotoCutscene("ending.pacifist")
        elseif kill then
            cutscene:loadMap("geno_room", "spawn")
            cutscene:gotoCutscene("ending.genocide")
        else
            error({msg = debug.traceback("Looks like you broke the game, and got NO ENDING AT ALL. Please report this, along with your best description of how this happened.")})
        end
    end,

    genocide = function(cutscene, event)
        Game.world.music:stop()
        Game.fader:fadeIn()
        local kris = cutscene:getCharacter("kris")
        local susie = cutscene:getCharacter("susie")
        local ralsei = cutscene:getCharacter("ralsei")
        local wilter = cutscene:getCharacter("wilter")
            cutscene:detachFollowers()
            --alert function
            local function alert(chara, duration)
                Assets.stopAndPlaySound("alert")
                chara.alert_icon = Sprite("effects/alert", chara.sprite.width/2)
                chara.alert_icon:setOrigin(0.5, 1)
                chara.alert_icon.layer = 100
                chara:addChild(chara.alert_icon)
                if duration then Game.world.timer:after(duration, function()
                    chara.alert_icon:remove()
                end) end
            end
            --damage function
            local function damage(chara, duration)
                Assets.stopAndPlaySound("damage")
                chara.damage_icon1 = Sprite("effects/attack/cut_1", chara.sprite.width/2)
                chara.damage_icon1:setOrigin(0.5, 0)
                chara.damage_icon1.layer = 100
                chara.damage_icon2 = Sprite("effects/attack/cut_2", chara.sprite.width/2)
                chara.damage_icon2:setOrigin(0.5, 0)
                chara.damage_icon2.layer = 100
                chara.damage_icon3 = Sprite("effects/attack/cut_3", chara.sprite.width/2)
                chara.damage_icon3:setOrigin(0.5, 0)
                chara.damage_icon3.layer = 100
                kris:setSprite("slash_1")
                chara:addChild(chara.damage_icon1)
                if duration then Game.world.timer:after(duration, function()
                    chara.damage_icon1:remove()
                    kris:setSprite("slash_2")
                    chara:addChild(chara.damage_icon2)
                    if duration then Game.world.timer:after(duration, function()
                        chara.damage_icon2:remove()
                        kris:setSprite("slash_3")
                        chara:addChild(chara.damage_icon3)
                        if duration then Game.world.timer:after(duration, function()
                            chara.damage_icon3:remove()
                            kris:setSprite("sword")
                        end) end
                    end) end
                end) end
                
            end
            --heavydamage function
            local function heavydamage(chara, duration)
                Assets.stopAndPlaySound("heavydamage")
                chara.damage_icon1 = Sprite("effects/attack/cut_1", chara.sprite.width/2)
                chara.damage_icon1:setOrigin(0.5, 0)
                chara.damage_icon1.layer = 100
                chara.damage_icon2 = Sprite("effects/attack/cut_2", chara.sprite.width/2)
                chara.damage_icon2:setOrigin(0.5, 0)
                chara.damage_icon2.layer = 100
                chara.damage_icon3 = Sprite("effects/attack/cut_3", chara.sprite.width/2)
                chara.damage_icon3:setOrigin(0.5, 0)
                chara.damage_icon3.layer = 100
                --spawns slash effects and animation
                kris:setSprite("slash_1")
                chara:addChild(chara.damage_icon1)
                if duration then Game.world.timer:after(duration, function()
                    chara.damage_icon1:remove()
                    kris:setSprite("slash_2")
                    chara:addChild(chara.damage_icon2)
                    if duration then Game.world.timer:after(duration, function()
                        chara.damage_icon2:remove()
                        kris:setSprite("slash_3")
                        chara:addChild(chara.damage_icon3)
                        if duration then Game.world.timer:after(duration, function()
                            chara.damage_icon3:remove()
                            kris:setSprite("sword")
                        end) end
                    end) end
                end) end
                
            end
            --starting the cutscene
            wilter:setSprite("death/dying1")
            cutscene:walkTo("kris", "kris1",0.1, "up")
            cutscene:walkTo("susie", "sus1",0.1, "up")
            cutscene:walkTo("ralsei", "ral1",0.1, "up")
            cutscene:fadeOut(0)
            cutscene:wait(2)
            kris:setSprite("sword")
            susie:setSprite("fell")
            ralsei:setSprite("splat")
            cutscene:fadeIn(2)
            cutscene:wait(1)
            cutscene:setSpeaker(wilter)
            cutscene:text("* Ugh.[wait:5].[wait:5].[wait:5] My head.[wait:5].[wait:5].")
            cutscene:text("* .[wait:5].[wait:5].")
            cutscene:text("* K-[wait:5] Kris?")
            cutscene:text("* Buddy?")
            cutscene:text("* A-[wait:5] Are you still there.[wait:5].[wait:5]?")
            cutscene:wait(1)
            alert(wilter)
            wilter:setSprite("death/dying2")
            cutscene:wait(0.5)
            wilter.alert_icon:remove()
            Game.world.music:play("g")
            cutscene:wait(0.5)
            cutscene:text("* K-[wait:5] Kris?")
            cutscene:text("* P-[wait:5] Please...")
            cutscene:text("* Put the weapon down...")
            cutscene:text("* Y-[wait:5] You don't have to do this.")
            cutscene:choicer({"Attack", "Do Not"})
            if cutscene.choice == 1 then
                wilter:setSprite("death/dying5")
                damage(wilter, 0.075)
                wilter:shake(4)
                kris:shake(1)
                cutscene:wait(0.5)
                cutscene:wait(0.5)
                cutscene:text("* K-[wait:5] Kris.")
                cutscene:text("* D-[wait:5] don't.[wait:5]\n* Please.")
                cutscene:choicer({"Attack", "Attack"})
                damage(wilter, 0.075)
                wilter:shake(5)
                kris:shake(1)
                wilter:setSprite("death/slmn1")
                cutscene:wait(0.5)
                cutscene:text("[voice:wilt2][shake:1]* S-[wait:5] She loves me.")
                cutscene:choicer({"Attack", "Attack"})
                damage(wilter, 0.075)
                wilter:shake(6)
                kris:shake(1)
                wilter:setSprite("death/slmn2")
                cutscene:wait(0.5)
                cutscene:text("[voice:wilt3][shake:2]* S-[wait:5] She loves me not.")
                cutscene:text("[shake:2]* O-[wait:5] Ouch.")
                cutscene:choicer({"Attack", "Attack"})
                damage(wilter, 0.075)
                wilter:shake(8)
                kris:shake(1)
                wilter:setSprite("death/slmn3")
                cutscene:wait(0.5)
                cutscene:text("[voice:wilt4][shake:3]* S-[wait:5] She loves m-[wait:5] me.")
                cutscene:text("[voice:wilt4][shake:3]* It.[wait:5].[wait:5].[wait:5] It hurts.")
                cutscene:choicer({"Attack", "Attack"})
                damage(wilter, 0.075)
                wilter:setSprite("death/slmn4")
                cutscene:wait(0.5)
                cutscene:text("[voice:wilt5][shake:4]* S-[wait:5] She l-[wait:5] loves me n-[wait:5] not.")
                cutscene:choicer({"Attack", "Attack"})
                damage(wilter, 0.075)
                wilter:shake(10)
                wilter:setSprite("death/slmn5")
                cutscene:wait(0.5)
                cutscene:text("[voice:wilt6][shake:5]* S-[wait:5] Sh[wait:1]e l-[wait:5] lo[wait:1]v[wait:1]es m-[wait:5]m[wait:1]e.")
                cutscene:wait(0.5)
                cutscene:choicer({"Attack", "Attack"})
                Game.world.music:pause()
                heavydamage(wilter, 0.075)
                wilter:shake(25)
                kris:shake(1)
                wilter:setSprite("death/dead1")
                cutscene:wait(4)
                wilter:setAnimation("death/dead")
                cutscene:wait(1.8)
                wilter:setSprite("death/dead15")
                cutscene:wait(2)
                cutscene:text("[voice:wilt6]* S-[wait:5] S[wait:1]h[wait:1]e[wait:1] l-[wait:5] l[wait:1]o[wait:1]v[wait:1]e[wait:1]s m-[wait:5] m[wait:1]e[wait:1] n[wait:1]o[wait:1]t[wait:1].")
                cutscene:text("[voice:wilt6]* A-[wait:5] A[wait:1]n[wait:1]d[wait:1] n[wait:1]o[wait:1]w[wait:1],[wait:5] s- [wait:5]s[wait:1]h[wait:1]e[wait:1] n[wait:1]e[wait:1]v[wait:1]e[wait:1]r[wait:1] w[wait:1]i[wait:1]l[wait:1]l[wait:1].")
            elseif cutscene.choice == 2 then
                Game.world.music:pause()
                cutscene:wait(1.5)
                Assets.stopAndPlaySound("equip")
                kris:setSprite("walk/up_1")
                kris:resetSprite()
                cutscene:wait(1.5)
                Game.world.music:play("wilter_pacifist")
                cutscene:setSpeaker(wilter)
                cutscene:text("* .[wait:5].[wait:5].")
                cutscene:text("* Heh[wait:5].[wait:5].")
                cutscene:text("* I guess I underestimated you,[wait:5] Kris.")
                cutscene:text("* You.[wait:5].[wait:5].")
                cutscene:text("* You're a lot stronger than I thought.")
                cutscene:text("* With that kind of power.")
                cutscene:text("* You could change the world.")
                cutscene:text("* But.")
                cutscene:text("* Why.[wait:5].[wait:5]?")
                wilter:setSprite("death/dying2")
                cutscene:text("* Why did you spare me?")
                cutscene:text("* I.[wait:5].[wait:10] I tried to kill you!")
                cutscene:text("* I don't understand.[wait:5].[wait:5].")
                cutscene:text("* WHY DIDN'T YOU FINISH THE JOB!?")
                wilter:setSprite("death/dying5")
                cutscene:text("* I hurt you.")
                cutscene:text("* I hurt your friends.")
                cutscene:text("* People like me.[wait:5].[wait:5].[wait:10] Don't deserve second chances.")
                cutscene:text("* We never deserve anything.")
                cutscene:text("* In the end,[wait:5] It all crumbles to dust.")
                cutscene:text("* Like nothing mattered.")
                cutscene:text("* Like we never mattered.")
                cutscene:text("* But you.[wait:5].[wait:5].")
                cutscene:text("* YOU matter.")
                cutscene:text("* ..[wait:5].")
                cutscene:text("* Maybe I can still be usefull to you.")
                cutscene:text("* Here,[wait:5] take this...")
                cutscene:walkTo("kris", "kris2", 1.5)
                cutscene:wait(2)
                cutscene:setSpeaker(default)
                Game.inventory:tryGiveItem("shadowcrystal")
                Assets.stopAndPlaySound("item")
                cutscene:text("* (You got ShadowCrystal.)")
                Game.inventory:tryGiveItem("thornweaver")
                Assets.stopAndPlaySound("item")
                cutscene:text("* (You got ThornWeaver.)")
                cutscene:walkTo("kris", "kris3", 0.5, "up")
                cutscene:wait(2)
                cutscene:setSpeaker(wilter)
                cutscene:text("[shake:1] * Now go on.[wait:5].[wait:5].")
                wilter:setSprite("death/dying4")
                cutscene:text("[shake:1] * I'll be...[wait:10] I'll be okay.")
            end
        cutscene:fadeOut(1)
        Game.world.music:fade(0, 1)
        cutscene:wait(1.5)
        wilter:remove()
        kris:setSprite("walk/up_1")
        Assets.stopAndPlaySound("deathnoise")
        cutscene:wait(1)
        if cutscene.choice == 1 then
            cutscene:setSpeaker(default)
            Game.inventory:tryGiveItem("shadowcrystal")
            Assets.stopAndPlaySound("item")
            cutscene:text("* (You got ShadowCrystal.)")
            Game.inventory:tryGiveItem("thornweaver")
            Assets.stopAndPlaySound("item")
            cutscene:text("* (You got ThornWeaver.)")
        end
        cutscene:wait(3)
        cutscene:fadeIn(3)
        cutscene:wait(4)
        cutscene:setSpeaker(susie)
        cutscene:text("* .[wait:2].[wait:2].", "bangs_neutral")
        Assets.stopAndPlaySound("wing")
        susie:shake(2)
        susie:setSprite("kneel_right")
        cutscene:wait(2)
        Assets.stopAndPlaySound("step1")
        susie:setSprite("walk/up_1")
        susie:shake(2)
        cutscene:wait(2)
        cutscene:text("* W-[wait:2] Wha?", "annoyed_down")
        cutscene:text("* .[wait:2].[wait:2].", "shy_down")
        cutscene:text("* I- [wait:2]Is he gone?", "nervous_side")
        cutscene:wait(2)
        Assets.stopAndPlaySound("step1")
        ralsei:setSprite("walk/up_1")
        ralsei:shake(2)
        cutscene:setSpeaker(ralsei)
        cutscene:text("* I-[wait:2] I don't see him anywhere.", "concern")
        susie:setSprite("walk/right_1")
        ralsei:setSprite("walk/left_1")
        cutscene:text("* He must've.[wait:2][wait:2].", "disappointed")
        cutscene:setSpeaker(susie)
        susie:setSprite("walk/left_1")
        cutscene:text("* He must've ran away.", "annoyed_down")
        susie:setSprite("walk/down_1")
        cutscene:text("* Well,[wait:2] good riddance,[wait:2] I guess.", "annoyed")
        cutscene:setSpeaker(ralsei)
        susie:setSprite("walk/up_1")
        ralsei:setSprite("walk/up_1")
        cutscene:text("* .[wait:2].[wait:2].", "disappointed")
        susie:setSprite("walk/right_1")
        cutscene:text("* Let's just.[wait:2].[wait:2].[wait:2] Go back to the studio.", "pensive")
        cutscene:setSpeaker(susie)
        cutscene:text("* Sure.", "annoyed_down")
        susie:setSprite("walk/left_1")
        cutscene:text("* I don't wanna be here for another second longer.", "bangs_neutral")
        susie:setSprite("walk/up_1")
        ralsei:setSprite("walk/up_1")
        cutscene:text("* Let's go.", "shy_down")
        kris:resetSprite()
        susie:resetSprite()
        ralsei:resetSprite()
        cutscene:attachFollowers()
        cutscene:alignFollowers()
        cutscene:attachCamera()
end
}