return {

    elevator = function (cutscene, event)
        if (Kristal.Config["skipto"] or "NONE") ~= "NONE" then
            return cutscene:gotoCutscene("intro.skip")
        end
        local kris = cutscene:getCharacter("kris")
        local susie = cutscene:getCharacter("susie")
        local ralsei = cutscene:getCharacter("ralsei")
        local door = Game.world.map:getEvent("elevator_door")
        assert(kris and susie and ralsei)
        Game:setFlag("tapecollect_a", false)
        Game:setFlag("tapecollect_b", false)
        Game:setFlag("tapecollect_c", false)
        Game:setFlag("tapeplayed_a", false)
        Game:setFlag("tapeplayed_b", false)
        Game:setFlag("tapeplayed_c", false)
        Game:setFlag("picture_collected", false)
        Game:setFlag("candy_taken", false)
        door:setPosition(11111111, 11111)
        cutscene:detachCamera()
        cutscene:detachFollowers()
        cutscene:fadeOut(0.00001)
        cutscene:wait(3)
        ralsei.y = ralsei.y + 1
        susie.y = susie.y + 2
        Assets.stopAndPlaySound("elecdoor_open")
        cutscene:fadeIn(1)
        cutscene:walkTo("susie", "kris2", 1)
        cutscene:wait(1)
        cutscene:walkTo("susie", "susie", 1)
        cutscene:walkTo("ralsei", "kris2", 1)
        cutscene:wait(1)
        susie:setSprite("wall_right")
        cutscene:walkTo("ralsei", "ralsei", 1)
        cutscene:walkTo("kris", "kris3", 1)
        cutscene:wait(1)
        cutscene:look("ralsei", "left")
        cutscene:walkTo("kris", "kris", 1)
        cutscene:wait(1)
        cutscene:look("kris", "up")
        Game.world.music:play("elevator")
        Game.world.music:fade(0, 0.00001)
        cutscene:wait(0.00001)
        Assets.stopAndPlaySound("noise")
        cutscene:wait(0.5)
        door:setPosition(284.00, 146.00)
        Assets.stopAndPlaySound("elecdoor_shut")
        door:setSprite("objects/elevator_open_3")
        cutscene:wait(0.05)
        door:setSprite("objects/elevator_open_2")
        cutscene:wait(0.05)
        Game.world.camera:shake(3)
        door:setSprite("objects/elevator_open_1")
        cutscene:wait(0.05)
        door:setSprite("objects/elevator_door")
        cutscene:wait(0.35)
        Game.world.music:fade(1, 2)
        cutscene:wait(3)
        cutscene:walkTo("kris", "kris2", 1, "left")
        cutscene:wait(1)
        cutscene:look("kris", "down")
        cutscene:wait(3)
        cutscene:setSpeaker(susie)
        cutscene:text("* ..[wait:5].", "neutral_side")
        cutscene:text("* So,[wait:5] uh.", "neutral")
        cutscene:text("* Are you sure you guys wanna do this?", "nervous_side")
        cutscene:text("* I mean,[wait:5] the chef[wait:5] DID[wait:5] warn us about that place.", "nervous")
        cutscene:setSpeaker(ralsei)
        cutscene:text("* Susie,[wait:5] don't worry!", "smile")
        cutscene:text("* I'm sure Kris knows what they're doing.", "pleased")
        cutscene:setSpeaker(susie)
        cutscene:text("* ..[wait:5].", "nervous_side")
        cutscene:text("* Well,[wait:5] if Kris said so.[wait:5].[wait:5]", "nervous")
        cutscene:wait(5)
        Game.world.music:fade(0, 0.5)
        cutscene:wait(1)
        Assets.stopAndPlaySound("bell")
        cutscene:wait(1)
        cutscene:setSpeaker(nil)
        cutscene:text("* THIS SECTOR DOES NOT EXIST,[wait:5] PLEASE PROCEED WITH CAUTION.", "pensive")
        cutscene:wait(1)
        Assets.stopAndPlaySound("elecdoor_open")
        door:setSprite("objects/elevator_open_1")
        cutscene:wait(0.05)
        door:setSprite("objects/elevator_open_2")
        cutscene:wait(0.05)
        door:setSprite("objects/elevator_open_3")
        cutscene:wait(0.05)
        door:remove()
        cutscene:wait(0.85)
        cutscene:setSpeaker(ralsei)
        cutscene:text("* We're here.", "pensive")
        cutscene:wait(1)
        kris:resetSprite()
        susie:resetSprite()
        cutscene:look("susie", "right")
        ralsei:resetSprite()
        cutscene:attachCamera()
        cutscene:interpolateFollowers()
        cutscene:attachFollowers()
        Game.world.music:stop()
        Game.world.music:fade(1, 0.000001)
    end,
    skip = function (cutscene)
        Game:setFlag("tapecollect_a", true)
        Game:setFlag("tapecollect_b", true)
        Game:setFlag("tapecollect_c", true)
        Game:setFlag("tapeplayed_a", true)
        Game:setFlag("tapeplayed_b", true)
        Game:setFlag("tapeplayed_c", true)
        if Kristal.Config["skipto"] == "CHASE" then
            Game:setPartyMembers("kris")
            cutscene:loadMap("wilters_room", "entry")
            cutscene:fadeOut(0.00001)
            cutscene:look("kris", "up")
            cutscene:fadeIn(1)
        elseif Kristal.Config["skipto"] == "FIGHT" then
            Game:setFlag("postchase", true)

            cutscene:loadMap("room1", "entry")
            cutscene:fadeOut(0.0001)
            cutscene:fadeIn(0.5)
        else
            error("Invalid skipto: "..Utils.dump(Kristal.Config["skipto"]))
        end
    end,
    intro = function(cutscene, event)
        local kris = cutscene:getCharacter("kris")
        local susie = cutscene:getCharacter("susie")
        local ralsei = cutscene:getCharacter("ralsei")
        local wilter = cutscene:getCharacter("wilter")
        if kris then
            
            -- Detach camera and followers (since characters will be moved)
            cutscene:detachCamera()
            cutscene:detachFollowers()
            wilter:setPosition(cutscene:getMarker("wilt"))
            wilter:setSprite("dark/darker")
            cutscene:walkTo("kris", "kris", 1.5, "up", true)
            cutscene:walkTo("susie", "susie", 1.5, "up", true)
            cutscene:wait(cutscene:walkTo("ralsei", "rals", 1.5, "up", true))
            cutscene:setSpeaker(wilter)
            wilter:setSprite("dark/dark")
            cutscene:text("* Kris..[wait:5].[wait:10]\n* Is that you?")
            wilter:setSprite("dark/darksmile")
            cutscene:text("* It must's be.[wait:10]\n* It's has to be's!")

            Assets.stopAndPlaySound("wilt_laugh_1")
            wilter:setAnimation("emotions/laugh")
            cutscene:wait(2)
            Game.world.music:play("wilter")
            wilter:setSprite("walk/down1")
            cutscene:text("* It's been's sooooooooo long's!")

            cutscene:setSpeaker(susie)
            cutscene:text("* Kris, we should go.[wait:10]\n* I don't like the look of this.", "sus_nervous")

            cutscene:setSpeaker(ralsei)
            cutscene:text("* Oh,[wait:5] come on Susie!", "pleased")
            cutscene:text("* He looks..[wait:5].[wait:10] relatively harmless.", "concern_smile")

            cutscene:setSpeaker(susie)
            cutscene:text("* Rals.[wait:10]\n * We don't even know who this guy is.", "suspicious")

            cutscene:setSpeaker(ralsei)
            cutscene:text("* Well sir.[wait:10]\n* What is your name?", "small_smile")

            cutscene:setSpeaker(wilter)
            cutscene:text("* My name's is Wilter.[wait:10]\n * Mr. Wilter.")
            cutscene:text("* I'm surprised you don't remember me..[wait:5]. \n[wait:10]* Azzy.")

            cutscene:setSpeaker(ralsei)
            cutscene:text("* Sorry sir.[wait:10]\n* But my name is Ralsei.", "pensive")

            cutscene:setSpeaker(wilter)
            cutscene:text("* My apologies's.")
            cutscene:text("* It's a pleasure's to meet's you two's!")

            cutscene:setSpeaker(ralsei)
            cutscene:text("* Well.[wait:10]\n* I've quite enjoyed our small chat.", "pleased")
            cutscene:text("* But we have to get going.", "pensive")

            Game.world.music:pause()
            wilter:setSprite("emotions/sad")
            cutscene:setSpeaker(wilter)
            cutscene:text("* You have to..[wait:5].[wait:10]\n * Leave..[wait:5].[wait:10]?")

            cutscene:setSpeaker(susie)
            cutscene:text("* Yes,[wait:10] we have to leave.", "smirk")
            cutscene:text("* I thought that was obvious.", "neutral")

            cutscene:setSpeaker(wilter)
            cutscene:text("* Please,[wait:10] don't go... ")
            cutscene:text("* I'm so alone down here.")

            cutscene:setSpeaker(ralsei)
            cutscene:text("* I'm sorry.", "frown")
            cutscene:text("* But we have to go and seal the fountain.", "disappointed")
            wilter:setSprite("emotions/verysad")
            cutscene:setSpeaker(wilter)
            cutscene:text("* So..[wait:5].\n[wait:10]* You're just going to leave me here.")
            cutscene:text("* Alone..[wait:5].[wait:10] Forever.")

            cutscene:setSpeaker(susie)
            cutscene:text("* Uhhhhhhhhhh.", "sus_nervous")
            cutscene:text("* Yeah,[wait:5] pretty much.", "smirk")
            susie:setSprite("shock_behind")
            ralsei:setSprite("shocked_behind")
            cutscene:setSpeaker(wilter)
            wilter:setSprite("emotions/stare")
            cutscene:text("[shake:2]* N-[wait:2] NO!")

            Assets.stopAndPlaySound("grab")
            kris:setSprite("vine")
            susie:setSprite("vine")
            ralsei:setSprite("vine")
            Game.world.camera:shake(7)
            cutscene:wait(1)
            wilter:setAnimation("emotions/laugh")
            Assets.stopAndPlaySound("wilt_laugh_2")
            cutscene:wait(2)
            Game.world.music:resume()
            wilter:setSprite("emotions/stare")

            cutscene:text("* You can't's just leaves's me agains's!")
            cutscene:text("* You's wouldn't leave's your best's friend behind's!")
            wilter:setSprite("emotions/sad")
            cutscene:text("* W-[wait:5] Would you?")

            

            cutscene:setSpeaker(susie)
            cutscene:text("* They're not your friend!!", "angry_c")

            cutscene:setSpeaker(wilter)
            wilter:setSprite("emotions/stare")
            cutscene:text("[shake:2]* SHUT[wait:2] UP.")
            cutscene:text("[shake:2]* I'M[wait:2] A[wait:2] BETTER[wait:2] FRIEND[wait:2] THAN[wait:2]\nYOU[wait:2] WILL[wait:2] EVER[wait:2] BE.")
            wilter:setAnimation("emotions/laugh")
            Assets.stopAndPlaySound("wilt_laugh_3")
            cutscene:wait(2)
            wilter:setSprite("walk/down1")
            cutscene:text("* Now,[wait:5] we're gonna play a game.")
            cutscene:text("* A wonderful game!")
            wilter:setSprite("emotions/stare")
            cutscene:text("[shake:2]* HIDE[wait:2] AND[wait:2] SEEK.")
            Assets.stopAndPlaySound("wilt_wonder", 2)
            cutscene:wait(5)
            wilter:setSprite("walk/down1")
            cutscene:text("* Remember's the rules!")
            wilter:setSprite("emotions/stare")
            cutscene:text("[shake:2]* DON'T.\n[wait:2]* GET.\n[wait:2]* CAUGHT.")
            wilter:setAnimation("emotions/laugh")
            Assets.stopAndPlaySound("wilt_laugh_1")
            Game.world.music:fade(0, 1)
            cutscene:fadeOut(1)
            cutscene:wait(1)
            Game.world:loadMap("main_room")
            Game.world.music:pause()
            cutscene:gotoCutscene("intro.intro2")
            
        end
    end,
    intro2 = function(cutscene, event)
        local kris = cutscene:getCharacter("kris")
        local susie = cutscene:getCharacter("susie")
        local ralsei = cutscene:getCharacter("ralsei")
        if kris then
            cutscene:walkTo(kris, "kris", 0.00001)
            cutscene:walkTo(susie, "susie", 0.1)
            cutscene:walkTo(ralsei, "ralsei", 0.1)
            cutscene:wait(1)
            kris:setSprite("sit")
            susie:setSprite("exasperated_right")
            ralsei:setSprite("walk_unhappy/left")
            cutscene:wait(1.5)
            cutscene:fadeIn(1)
            cutscene:setSpeaker(susie)
            susie:shake(4)
            cutscene:text("* Kris,[wait:5] dude!!", "angry_c")
            susie:shake(4)
            cutscene:text("* Will you[wait:2] GET[wait:2] UP[wait:2] already!?", "angry")
            cutscene:wait(2)
            kris:shake(4)
            Assets.stopAndPlaySound("wing")
            cutscene:wait(2)
            Assets.stopAndPlaySound("step1")
            kris:shake(4)
            kris:setSprite("walk/left")
            ralsei:setSprite("walk/left")
            susie:setSprite("walk/right")
            cutscene:wait(2)
            kris:setSprite("walk/right")
            cutscene:setSpeaker(ralsei)
            cutscene:text("* Kris,[wait:5] are you okay?", "frown")
            cutscene:text("* You look..[wait:5].[wait:10] Hurt.", "frown_b")
            cutscene:text("* I'm sorry.", "disappointed")
            cutscene:text("* That Wilter fellow was more dangerous than I thought.", "no_glasses_closed")
            kris:setSprite("walk/left")
            cutscene:setSpeaker(susie)
            cutscene:text("* Yea!\n[wait:10]* I told you!", "angry_b")
            cutscene:text("* I knew we should've left!", "teeth")
            cutscene:text("* Now,[wait:5] we're trapped in his STUPID funhouse!", "shy")
            cutscene:text("* AND WE DON'T KNOW HOW TO LEAVE!!!!", "teeth_b")
            kris:setSprite("walk/right")
            cutscene:setSpeaker(ralsei)
            cutscene:text("* Susie,[wait:5] there has to be some sort of [color:yellow]KEY[color:reset] somewhere.", "pensive")
            cutscene:text("* How else would he have trapped us here in the first place?", "concern_smile")
            kris:setSprite("walk/left")
            cutscene:setSpeaker(susie)
            cutscene:text("* ..[wait:5].", "nervous")
            cutscene:text("* Yeah,[wait:5] you're right.", "neutral_side")
            cutscene:text("* I just hope we won't be here for long..[wait:5].", "nervous")
            cutscene:text("* Lead the way,[wait:5] Kris.", 'smirk')
            kris:resetSprite()
            susie:resetSprite()
            ralsei:resetSprite()
            cutscene:attachFollowers()
            cutscene:attachCamera()
            cutscene:alignFollowers()
            cutscene:wait(0.5)
            Game.world.music:play("garden")
            cutscene:endCutscene()
        end
    end,
    outro = function(cutscene, event)
        cutscene:wait(cutscene:fadeOut(0.5))
        cutscene:wait(0.5)

        local thanktext = Text("[font:main,64][color:yellow]Thanks For Playing!", 800, 170, {align="center"})
        thanktext:setOrigin(0.5, 0)
        thanktext.alpha = 0
        Game.stage:addChild(thanktext)

        Assets.stopAndPlaySound("spare")
        Game.stage.timer:tween(0.5, thanktext, {x=320,alpha=1}, "out-quad")
        cutscene:wait(1.5)

        Assets.stopAndPlaySound("mode", 1, 1)

        local text1 = Text("[font:main,32][color:cyan]Stay tuned for more DELTARUNE: UZUMAKI!", 320, 230, {align="center"})
        text1:setOrigin(0.5, 0)
        Game.stage:addChild(text1)
        cutscene:wait(2)

        Assets.stopAndPlaySound("mode", 1, 1.25)

        local text2 = Text("[font:main,16]Check us out on YouTube! (RazFraz)", 320, 280, {align="center"})
        text2:setOrigin(0.5, 0)
        Game.stage:addChild(text2)
        cutscene:wait(2)

        Assets.stopAndPlaySound("mode", 1, 1.5)

        local text3 = Text("[font:main,16]Check us out on Soundcloud! (Deltarune: UZUMAKI)", 320, 310, {align="center"})
        text3:setOrigin(0.5, 0)
        Game.stage:addChild(text3)
        cutscene:wait(2)

        Assets.stopAndPlaySound("mode", 1, 1.75)

        local text4 = Text("[font:main,16]Please.", 320, 340, {align="center"})
        text4:setOrigin(0.5, 0)
        Game.stage:addChild(text4)
        cutscene:wait(2)

        Assets.stopAndPlaySound("mode", 1, 2)

        local text5 = Text("[font:main,16]...", 320, 370, {align="center"})
        text5:setOrigin(0.5, 0)
        Game.stage:addChild(text5)
        cutscene:wait(2)

        Assets.stopAndPlaySound("mode", 1, 2.25)

        local text6 = Text("[font:main,16]Okay bye", 320, 400, {align="center"})
        text6:setOrigin(0.5, 0)
        Game.stage:addChild(text6)

        cutscene:wait(2)

        thanktext:fadeOutAndRemove(3)
        text1:fadeOutAndRemove(3)
        text2:fadeOutAndRemove(3)
        text3:fadeOutAndRemove(3)
        text4:fadeOutAndRemove(3)
        text5:fadeOutAndRemove(3)
        text6:fadeOutAndRemove(3)

        cutscene:wait(5)

        local extra = Text("[font:main,32][color:yellow]Extras Unlocked!", 800, 280, {align="center"})
        extra:setOrigin(0.5, 0)
        extra.alpha = 0
        Game.stage:addChild(extra)

        Assets.stopAndPlaySound("spare")
        Game.stage.timer:tween(0.5, extra, {x=320,alpha=1}, "out-quad")
        cutscene:wait(2)
        Assets.stopAndPlaySound("spare")
        Game.stage.timer:tween(0.5, extra, {x=-480,alpha=0}, "in-quad")
    
        cutscene:wait(1)

        Kristal.Config["GameBeaten"] = true
        Kristal.Config["debug"] = true
        Game.state = "EXIT"
        Game.fader:fadeOut(function()
            Kristal.returnToMenu()
        end, {speed = 1})
    end

}
