return {
    cutscene1 = function(cutscene, event)
        if not Game:getFlag("fight_attempted") then
            Game:setFlag("fight_attempted", true)
            Game:saveQuick()
            local kris = cutscene:getCharacter("kris")
            local susie = cutscene:getCharacter("susie")
            local ralsei = cutscene:getCharacter("ralsei")
            local omeg_wilter = cutscene:getCharacter("omeg_wilter")
            local black = Game.world.map:getEvent("dark_overlay")
            if kris then
                Game.world.music:setVolume(1)
                cutscene:detachFollowers()

                local x = event.x + event.width/2
                local y = event.y + event.height/2
                cutscene:setSpeaker(ralsei)
                omeg_wilter:setSprite("black")
                cutscene:text("* Wait,[wait:5] stop!", "shock")
                cutscene:setSpeaker(omeg_wilter)
                cutscene:slideTo("omeg_wilter", "wilter_1",0.5)
                cutscene:wait(0.4)
                Game.world.timer:tween(0.2, omeg_wilter, {scale_x = 2.5, scale_y = 1.5})
                Game.world.camera:shake(7)
                kris:setSprite("sit")
                susie:setSprite("kneel_right")
                ralsei:setSprite("splat")
                Assets.stopAndPlaySound("impact")
                cutscene:wait(0.1)
                cutscene:slideTo("kris", "kris_1", 0.5, "out-circ")
                cutscene:slideTo("susie", "sus_1", 0.5, "out-circ")
                cutscene:slideTo("ralsei", "ral_1", 0.5, "out-circ")
                cutscene:wait(0.1)
                Game.world.timer:tween(0.2, omeg_wilter, {scale_x = 2, scale_y = 2}, "out-bounce")
                cutscene:wait(1.3)
                black:remove()
                Assets.stopAndPlaySound("noise")
                omeg_wilter:setSprite("walk/down_1")
                Game.world.music:play("prebattle",1)
                cutscene:text("* You...[wait:10]")
                cutscene:text("* You's thought...[wait:10]")
                omeg_wilter:setSprite("insane")
                cutscene:text("* You's thought you's could run's from me?!")
                omeg_wilter:setAnimation("laugh")
                Assets.stopAndPlaySound("wilt_big_laugh")
                cutscene:wait(2.5)
                omeg_wilter:setSprite("walk/down_1")
                cutscene:text("* Heh[wait:5].[wait:5].[wait:5].[wait:5]")
                cutscene:text("* You've grown so predictable..[wait:5] Kris.[wait:10]\n* You haven't changed at all.")
                cutscene:text("* You're just the same,[wait:10] old,[wait:10] scared little child.")
                omeg_wilter:setSprite("insane")
                cutscene:text("* So helpless,[wait:10]\n* so... [wait:10]W[wait:1]E[wait:1]A[wait:1]K. ")
                omeg_wilter:setSprite("walk/down_1")
                cutscene:text("* But once again's,[wait:10]\n* The curtain's are coming's to a close.")
                omeg_wilter:setSprite("down_sad")
                cutscene:text("* I don't want to be alone again...")
                omeg_wilter:setSprite("verysad")
                cutscene:text("* I[wait:5] can't[wait:5] be alone again...")
                cutscene:text("* .[wait:5].[wait:5].")
                omeg_wilter:setSprite("walk/down_1")
                cutscene:text("* Kris,[wait:10] you...[wait:5] \n* You want to keep playing,[wait:5] don't you?")
                omeg_wilter:setSprite("insane")
                cutscene:text("* Then let's play,[wait:10]\nlet's play forever's!")
                Assets.stopAndPlaySound("wilt_bg_wonder")
                cutscene:text("* It will's be WONDERFULL!")
                omeg_wilter:setAnimation("laugh")
                Assets.stopAndPlaySound("wilt_epic_laugh")
                cutscene:wait(5.5)
                omeg_wilter:setSprite("down_sad")
                cutscene:text("* Goodbye...[wait:10]\nOld friend...")
                Game.world.music:stop()
                Game:setFlag("first_time", false)
                cutscene:startEncounter("wilter", true, {omeg_wilter})
                cutscene:gotoCutscene("ending.endingcheck")
            end
        else
            cutscene:gotoCutscene("wilt_omeg_intro.cutscene2")
        end
    end,



        cutscene2 = function(cutscene, event)
            local kris = cutscene:getCharacter("kris")
            local susie = cutscene:getCharacter("susie")
            local ralsei = cutscene:getCharacter("ralsei")
            local omeg_wilter = cutscene:getCharacter("omeg_wilter")
            local black = Game.world.map:getEvent("dark_overlay")
            if kris then
                Game.world.music:setVolume(1)
                cutscene:detachFollowers()
                omeg_wilter:setSprite("black")
                cutscene:slideTo("omeg_wilter", "wilter_1",0.5)
                cutscene:wait(0.4)
                Game.world.timer:tween(0.2, omeg_wilter, {scale_x = 2.5, scale_y = 1.5})
                Game.world.camera:shake(7)
                kris:setSprite("sit")
                susie:setSprite("kneel_right")
                ralsei:setSprite("splat")
                Assets.stopAndPlaySound("impact")
                cutscene:wait(0.1)
                cutscene:slideTo("kris", "kris_1", 0.5, "out-circ")
                cutscene:slideTo("susie", "sus_1", 0.5, "out-circ")
                cutscene:slideTo("ralsei", "ral_1", 0.5, "out-circ")
                cutscene:wait(0.1)
                Game.world.timer:tween(0.2, omeg_wilter, {scale_x = 2, scale_y = 2}, "out-bounce")
                cutscene:wait(1.3)
                black:remove()
                Assets.stopAndPlaySound("noise")
                omeg_wilter:setSprite("walk/down_1") 
                Game.world.music:play("prebattle")
                omeg_wilter:setAnimation("laugh")
                Assets.stopAndPlaySound("wilt_epic_laugh")
                cutscene:wait(5.5)
                Game.world.music:stop()
                Mod.attempted = true
                cutscene:startEncounter("wilter", true, {omeg_wilter})
                cutscene:gotoCutscene("ending.endingcheck")
            end
     end
}