return {
  version = "1.11",
  luaversion = "5.1",
  tiledversion = "1.11.0",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 16,
  height = 14,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 6,
  nextobjectid = 45,
  properties = {
    ["music"] = "garden"
  },
  tilesets = {
    {
      name = "bedroom",
      firstgid = 1,
      filename = "../tilesets/bedroom.tsx",
      exportfilename = "../tilesets/bedroom.lua"
    },
    {
      name = "funhouse_objects",
      firstgid = 197,
      filename = "../tilesets/funhouse_objects.tsx",
      exportfilename = "../tilesets/funhouse_objects.lua"
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 16,
      height = 14,
      id = 1,
      name = "Tile Layer 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 0,
        0, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 0,
        0, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 0,
        0, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 0,
        0, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 0,
        0, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 0,
        0, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 0,
        0, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 0,
        0, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 0,
        0, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 0,
        0, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 0,
        0, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 0,
        0, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 0,
        0, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 0
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 44.8604,
          y = 67.0493,
          width = 125.416,
          height = 218.513,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 167.865,
          y = 128.793,
          width = 102.262,
          height = 77.1791,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 261.444,
          y = 64.1551,
          width = 201.63,
          height = 106.121,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          type = "",
          shape = "rectangle",
          x = 364.189,
          y = 128.31,
          width = 102.262,
          height = 77.1791,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          type = "",
          shape = "rectangle",
          x = 462.472,
          y = 64.1443,
          width = 125.416,
          height = 218.513,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 0,
          width = 40,
          height = 560,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 0,
          width = 40,
          height = 560,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = 378.107,
          y = 480.566,
          width = 181.893,
          height = 79.4342,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "",
          type = "",
          shape = "rectangle",
          x = 485.193,
          y = 438.26,
          width = 87.9164,
          height = 23.7969,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 89.2385,
          y = 343.072,
          width = 36.3564,
          height = 31.7292,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 479.905,
          width = 161.935,
          height = 80.0952,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 485.854,
          y = 296.14,
          width = 64.7805,
          height = 53.5431,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 370.175,
          y = 345.056,
          width = 46.9328,
          height = 22.4749,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 344.395,
          y = 221.444,
          width = 9.25436,
          height = 7.93231,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "",
          shape = "rectangle",
          x = 321.259,
          y = 191.036,
          width = 14.5426,
          height = 13.2205,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 294.157,
          y = 186.409,
          width = 14.5426,
          height = 11.2374,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "",
          type = "",
          shape = "rectangle",
          x = 300.106,
          y = 172.528,
          width = 14.5426,
          height = 15.2036,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "",
          type = "",
          shape = "rectangle",
          x = 303.411,
          y = 214.172,
          width = 17.8477,
          height = 11.2374,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "",
          type = "",
          shape = "rectangle",
          x = 166.039,
          y = 328.234,
          width = 39.2036,
          height = 26.9045,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "",
          type = "",
          shape = "rectangle",
          x = 441.315,
          y = 460.563,
          width = 18.3099,
          height = 19.2488,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 31,
          name = "spawn",
          type = "",
          shape = "point",
          x = 310.783,
          y = 538.185,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "",
          type = "",
          shape = "rectangle",
          x = 50,
          y = 108,
          width = 126,
          height = 122,
          rotation = 0,
          gid = 218,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 480,
          width = 22,
          height = 30,
          rotation = 0,
          gid = 216,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 294.485,
          y = 232.853,
          width = 62,
          height = 60,
          rotation = 0,
          gid = 217,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 157.688,
          y = 362.137,
          width = 54,
          height = 66,
          rotation = 0,
          gid = 220,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 360,
          width = 70,
          height = 70,
          rotation = 0,
          gid = 219,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 368.139,
          y = 371.995,
          width = 52,
          height = 30,
          rotation = 0,
          gid = 221,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "chest",
          type = "",
          shape = "point",
          x = 220,
          y = 151.556,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["item"] = "silver_card"
          }
        },
        {
          id = 33,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 480.398,
          y = 291.241,
          width = 78.0647,
          height = 68.6283,
          rotation = 0,
          visible = true,
          properties = {
            ["text1"] = "* (It's a group of plush dolls.)",
            ["text2"] = "* (One has been torn apart.)"
          }
        },
        {
          id = 34,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 320,
          width = 51.8899,
          height = 40.2985,
          rotation = 0,
          visible = true,
          properties = {
            ["text"] = "* (It's a broken spotlight, looks non-functional.)"
          }
        },
        {
          id = 36,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 357.276,
          y = 157.903,
          width = 107.395,
          height = 48.7531,
          rotation = 0,
          visible = true,
          properties = {
            ["text1"] = "* (You look into the drawer.)",
            ["text2"] = "* (.[wait:2].[wait:2].[wait:2]It's empty.)"
          }
        },
        {
          id = 37,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 294.008,
          y = 173.853,
          width = 60.0772,
          height = 55.2927,
          rotation = 0,
          visible = true,
          properties = {
            ["text1"] = "* (It's some toy blocks scattered about.)"
          }
        },
        {
          id = 39,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 359.114,
          y = 333.645,
          width = 67.0685,
          height = 45.8443,
          rotation = 0,
          visible = true,
          properties = {
            ["text1"] = "* (It's a broken toy car.)"
          }
        },
        {
          id = 40,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 432.125,
          y = 449.953,
          width = 33.9587,
          height = 35.6567,
          rotation = 0,
          visible = true,
          properties = {
            ["text"] = "* (It's some empty soda cans.)"
          }
        },
        {
          id = 41,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 72.1623,
          y = 447.406,
          width = 61.9747,
          height = 37.3546,
          rotation = 0,
          visible = true,
          properties = {
            ["text"] = "* (Moss.)"
          }
        },
        {
          id = 43,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 451.678,
          y = 166.835,
          width = 107.395,
          height = 120.689,
          rotation = 0,
          visible = true,
          properties = {
            ["text1"] = "* (It's a neatly made bed.)"
          }
        },
        {
          id = 44,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 560,
          width = 200,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["exit_sound"] = "doorclose",
            ["map"] = "rng_door",
            ["marker"] = "door",
            ["sound"] = "dooropen"
          }
        }
      }
    },
    {
      type = "imagelayer",
      image = "../../../assets/sprites/filters/black.png",
      id = 5,
      name = "Image Layer 1",
      class = "",
      visible = true,
      opacity = 0.5,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = false,
      repeaty = false,
      properties = {}
    }
  }
}
