return {
  version = "1.11",
  luaversion = "5.1",
  tiledversion = "1.11.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 16,
  height = 12,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 7,
  nextobjectid = 52,
  properties = {
    ["music"] = "garden"
  },
  tilesets = {
    {
      name = "garden",
      firstgid = 1,
      filename = "../tilesets/garden.tsx",
      exportfilename = "../tilesets/garden.lua"
    },
    {
      name = "tape",
      firstgid = 193,
      filename = "../tilesets/tape.tsx",
      exportfilename = "../tilesets/tape.lua"
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 16,
      height = 12,
      id = 1,
      name = "Tile Layer 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 34, 35, 36, 37, 37, 37, 37, 41, 42, 42, 42, 45, 46, 46, 1,
        1, 50, 51, 52, 53, 54, 54, 54, 54, 54, 54, 54, 61, 54, 54, 1,
        1, 66, 67, 68, 68, 68, 71, 68, 68, 68, 75, 76, 68, 68, 68, 1,
        1, 82, 83, 84, 84, 84, 84, 84, 84, 90, 91, 92, 92, 94, 95, 1,
        113, 98, 99, 100, 101, 102, 103, 104, 105, 105, 107, 108, 109, 105, 105, 1,
        113, 114, 105, 116, 117, 118, 119, 120, 121, 122, 123, 105, 105, 126, 105, 1,
        1, 130, 131, 105, 105, 105, 135, 136, 137, 138, 105, 140, 105, 105, 143, 1,
        1, 146, 147, 148, 105, 105, 151, 152, 153, 105, 155, 156, 157, 158, 159, 1,
        1, 162, 163, 105, 165, 105, 167, 105, 105, 105, 171, 105, 105, 174, 175, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 479.696,
          y = 381.543,
          width = 14.4342,
          height = 14.9153,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 499.423,
          y = 361.336,
          width = 18.2833,
          height = 17.321,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 459.969,
          y = 242.494,
          width = 16.3587,
          height = 14.9153,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440.724,
          y = 261.259,
          width = 13.953,
          height = 14.4342,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 80,
          width = 40,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 80,
          width = 560,
          height = 120,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = 600,
          y = 80,
          width = 40,
          height = 360,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 440,
          width = 640,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 320,
          width = 40,
          height = 120,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "",
          type = "",
          shape = "rectangle",
          x = 402,
          y = 402,
          width = 36,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "",
          type = "",
          shape = "rectangle",
          x = 562,
          y = 324.667,
          width = 36,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "",
          type = "",
          shape = "rectangle",
          x = 84,
          y = 244,
          width = 34,
          height = 29.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "",
          type = "",
          shape = "rectangle",
          x = 149.333,
          y = 257.667,
          width = 72.6667,
          height = 35,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "",
          type = "",
          shape = "rectangle",
          x = 521.333,
          y = 399,
          width = 72,
          height = 31.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "",
          type = "",
          shape = "rectangle",
          x = 276,
          y = 296.667,
          width = 86,
          height = 40.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "",
          type = "",
          shape = "polygon",
          x = 403.333,
          y = 306.667,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 29.6667, y = -48 },
            { x = 37, y = -48 },
            { x = 36.6667, y = 7.66667 },
            { x = 0.333333, y = 8 }
          },
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 18,
          name = "spawn",
          type = "",
          shape = "point",
          x = 52.6645,
          y = 281.175,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 19,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = -40,
          y = 240,
          width = 40,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {
            ["map"] = "vines_room_1",
            ["marker"] = "garden"
          }
        },
        {
          id = 31,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 402.466,
          y = 256.261,
          width = 37.4387,
          height = 57.1263,
          rotation = 0,
          visible = true,
          properties = {
            ["text"] = "* It's a dirty shovel."
          }
        },
        {
          id = 38,
          name = "npc",
          type = "",
          shape = "point",
          x = 319,
          y = 308,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["actor"] = "tape",
            ["cutscene"] = "generic.tapecollect_c",
            ["flagcheck"] = "!tapecollect_c"
          }
        }
      }
    },
    {
      type = "imagelayer",
      image = "../../../assets/sprites/filters/black.png",
      id = 6,
      name = "Image Layer 1",
      class = "",
      visible = true,
      opacity = 0.5,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = false,
      repeaty = false,
      properties = {}
    }
  }
}
