return {
  version = "1.11",
  luaversion = "5.1",
  tiledversion = "1.11.0",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 19,
  height = 16,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 7,
  nextobjectid = 90,
  properties = {
    ["border"] = "simple",
    ["music"] = "garden",
    ["name"] = "Funhouse - Entrance"
  },
  tilesets = {
    {
      name = "funhouse",
      firstgid = 1,
      filename = "../tilesets/funhouse.tsx"
    },
    {
      name = "flower_decal",
      firstgid = 118,
      filename = "../tilesets/flower_decal.tsx",
      exportfilename = "../tilesets/flower_decal.lua"
    },
    {
      name = "door",
      firstgid = 143,
      filename = "../tilesets/door.tsx"
    },
    {
      name = "light_right",
      firstgid = 144,
      filename = "../tilesets/light_right.tsx"
    },
    {
      name = "light_left",
      firstgid = 145,
      filename = "../tilesets/light_left.tsx"
    },
    {
      name = "funhouse_objects",
      firstgid = 146,
      filename = "../tilesets/funhouse_objects.tsx",
      exportfilename = "../tilesets/funhouse_objects.lua"
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 19,
      height = 16,
      id = 1,
      name = "Tile Layer 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 8, 0, 33, 33, 33, 33, 33, 33, 33, 33, 33, 0, 8, 0, 0, 0,
        8, 0, 0, 0, 35, 59, 59, 59, 59, 59, 59, 59, 29, 59, 31, 0, 0, 20, 0,
        0, 0, 20, 34, 48, 59, 42, 59, 59, 59, 59, 59, 59, 59, 44, 32, 0, 0, 0,
        33, 33, 33, 47, 48, 27, 28, 59, 59, 59, 59, 59, 1, 2, 44, 19, 33, 33, 33,
        59, 59, 59, 47, 48, 40, 41, 59, 59, 59, 59, 59, 14, 15, 44, 45, 59, 59, 59,
        59, 59, 59, 21, 61, 72, 72, 72, 72, 72, 72, 72, 72, 72, 57, 45, 3, 59, 59,
        59, 59, 16, 60, 74, 85, 85, 85, 85, 85, 85, 85, 85, 85, 70, 58, 59, 59, 59,
        72, 72, 72, 73, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 71, 72, 72, 72,
        85, 85, 85, 85, 84, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85,
        85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85,
        85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 86, 85, 85, 85, 85, 85,
        98, 98, 98, 99, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 97, 98, 98, 98,
        0, 0, 0, 112, 99, 85, 87, 85, 85, 85, 85, 85, 85, 85, 97, 110, 0, 20, 0,
        0, 0, 0, 0, 112, 98, 98, 98, 100, 85, 109, 98, 98, 98, 110, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 8, 113, 85, 111, 0, 0, 0, 0, 8, 0, 0, 0,
        0, 0, 0, 20, 0, 0, 0, 0, 113, 85, 111, 0, 20, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 19,
      height = 16,
      id = 2,
      name = "Tile Layer 2",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 36, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0,
        0, 0, 0, 36, 117, 0, 0, 0, 119, 120, 121, 0, 0, 0, 76, 10, 0, 0, 0,
        33, 33, 33, 116, 0, 0, 0, 123, 124, 125, 126, 127, 0, 0, 0, 78, 33, 33, 33,
        59, 59, 59, 0, 0, 0, 0, 128, 129, 130, 131, 132, 0, 0, 0, 0, 59, 59, 59,
        0, 0, 0, 0, 0, 0, 0, 133, 134, 135, 136, 137, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 138, 139, 140, 141, 142, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 520,
          width = 200,
          height = 120,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 440,
          width = 120,
          height = 200,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 520,
          width = 200,
          height = 120,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 440,
          width = 120,
          height = 200,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 0,
          width = 360,
          height = 240,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 120,
          width = 120,
          height = 200,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 120,
          width = 120,
          height = 200,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 40,
          width = 80,
          height = 200,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 40,
          width = 80,
          height = 200,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "",
          type = "",
          shape = "polygon",
          x = 120,
          y = 320,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 80, y = -80 },
            { x = 0, y = 0 }
          },
          properties = {}
        },
        {
          id = 47,
          name = "",
          type = "",
          shape = "polygon",
          x = 640,
          y = 320,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -80, y = -80 },
            { x = 0, y = -80 }
          },
          properties = {}
        },
        {
          id = 48,
          name = "",
          type = "",
          shape = "polygon",
          x = 640,
          y = 520,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = -80 },
            { x = -80, y = 0 }
          },
          properties = {}
        },
        {
          id = 49,
          name = "",
          type = "",
          shape = "polygon",
          x = 200,
          y = 520,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -80, y = -80 },
            { x = -80, y = 0 }
          },
          properties = {}
        },
        {
          id = 60,
          name = "",
          type = "",
          shape = "rectangle",
          x = 252.738,
          y = 454.06,
          width = 15.024,
          height = 12.687,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "",
          type = "",
          shape = "rectangle",
          x = 173.11,
          y = 414.663,
          width = 15.024,
          height = 12.687,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "",
          type = "",
          shape = "rectangle",
          x = 492.288,
          y = 454.394,
          width = 15.024,
          height = 12.687,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "",
          type = "",
          shape = "rectangle",
          x = 572.416,
          y = 415.665,
          width = 15.024,
          height = 12.687,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 88,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 640,
          width = 120,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 50,
          name = "entry",
          type = "",
          shape = "point",
          x = 379.582,
          y = 627.545,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "exit1",
          type = "",
          shape = "point",
          x = 19.2309,
          y = 380.256,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "exit2",
          type = "",
          shape = "point",
          x = 740.339,
          y = 381.265,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "spawn",
          type = "",
          shape = "point",
          x = 540.837,
          y = 305.036,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 69,
          name = "kris",
          type = "",
          shape = "point",
          x = 380.347,
          y = 505.333,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 70,
          name = "susie",
          type = "",
          shape = "point",
          x = 321.086,
          y = 494.559,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 71,
          name = "ralsei",
          type = "",
          shape = "point",
          x = 438.53,
          y = 487.016,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 73,
          name = "kris_2",
          type = "",
          shape = "point",
          x = 379.261,
          y = 365.317,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 74,
          name = "susie_2",
          type = "",
          shape = "point",
          x = 320,
          y = 354.543,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 75,
          name = "ralsei_2",
          type = "",
          shape = "point",
          x = 437.444,
          y = 347,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 79,
          name = "gathering_left",
          type = "",
          shape = "point",
          x = 320.639,
          y = 419.169,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 85,
          name = "gathering_right",
          type = "",
          shape = "point",
          x = 440,
          y = 419.169,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 3,
          name = "light_right",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 440,
          width = 40,
          height = 80,
          rotation = 0,
          gid = 144,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "light_right",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 480,
          width = 40,
          height = 80,
          rotation = 0,
          gid = 144,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "light_left",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 480,
          width = 40,
          height = 80,
          rotation = 0,
          gid = 145,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "light_left",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 440,
          width = 40,
          height = 80,
          rotation = 0,
          gid = 145,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "door",
          type = "",
          shape = "rectangle",
          x = 760,
          y = 240,
          width = 40,
          height = 80,
          rotation = 0,
          gid = 143,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "savepoint",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 280,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["text1"] = "* This place, while terrifying.",
            ["text2"] = "* It feels so... familiar.",
            ["text3"] = "* You're filled with the power of twisted nostalgia."
          }
        },
        {
          id = 64,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 200,
          width = 40,
          height = 55.2938,
          rotation = 0,
          visible = true,
          properties = {
            ["text"] = "* This wall is suspiciously doorless."
          }
        },
        {
          id = 66,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 760,
          y = 320,
          width = 40,
          height = 120,
          rotation = 0,
          visible = true,
          properties = {
            ["map"] = "hallway1",
            ["marker"] = "entrance"
          }
        },
        {
          id = 68,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = -40,
          y = 320,
          width = 40,
          height = 120,
          rotation = 0,
          visible = true,
          properties = {
            ["map"] = "hallway2",
            ["marker"] = "entrance"
          }
        },
        {
          id = 77,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 359.487,
          y = 391.553,
          width = 41.6224,
          height = 63.1233,
          rotation = 0,
          visible = true,
          properties = {
            ["cutscene"] = "generic.doorappear",
            ["once"] = false,
            ["solid"] = false
          }
        },
        {
          id = 86,
          name = "script",
          type = "",
          shape = "rectangle",
          x = -100.399,
          y = -23.3004,
          width = 1078.04,
          height = 787.501,
          rotation = 0,
          visible = true,
          properties = {
            ["cutscene"] = "generic.projector_check",
            ["once"] = false
          }
        },
        {
          id = 89,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 640,
          width = 120,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["text1"] = "* Locked."
          }
        }
      }
    },
    {
      type = "imagelayer",
      image = "../../../assets/sprites/filters/black.png",
      id = 6,
      name = "Image Layer 1",
      class = "",
      visible = true,
      opacity = 0.5,
      offsetx = 0,
      offsety = 1,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = false,
      repeaty = false,
      properties = {}
    }
  }
}
