return {
  version = "1.11",
  luaversion = "5.1",
  tiledversion = "1.11.0",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 16,
  height = 12,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 9,
  nextobjectid = 62,
  properties = {
    ["music"] = "garden"
  },
  tilesets = {
    {
      name = "puppetroom",
      firstgid = 1,
      filename = "../tilesets/puppetroom.tsx",
      exportfilename = "../tilesets/puppetroom.lua"
    },
    {
      name = "funhouse_objects",
      firstgid = 145,
      filename = "../tilesets/funhouse_objects.tsx",
      exportfilename = "../tilesets/funhouse_objects.lua"
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 16,
      height = 12,
      id = 1,
      name = "Tile Layer 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 0, 0,
        0, 0, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 0, 0,
        0, 0, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 0, 0,
        0, 0, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 0, 0,
        0, 0, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 0, 0,
        0, 0, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 0, 0,
        0, 0, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 0, 0,
        0, 0, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 0, 0,
        0, 0, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 0, 0,
        0, 0, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 0, 0,
        0, 0, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 0, 0,
        0, 0, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 0, 0
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "objects_underparty",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 158,
          y = 128,
          width = 102,
          height = 128,
          rotation = 0,
          gid = 174,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          type = "",
          shape = "rectangle",
          x = 272,
          y = 88,
          width = 102,
          height = 128,
          rotation = 0,
          gid = 174,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 120,
          width = 102,
          height = 128,
          rotation = 0,
          gid = 174,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "objects_party",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "",
          type = "",
          shape = "rectangle",
          x = 218,
          y = 256,
          width = 206,
          height = 128,
          rotation = 0,
          gid = 180,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "puppet",
          type = "",
          shape = "rectangle",
          x = 268,
          y = 214,
          width = 26,
          height = 50,
          rotation = 0,
          gid = 178,
          visible = true,
          properties = {
            ["chara"] = "kr"
          }
        },
        {
          id = 3,
          name = "puppet",
          type = "",
          shape = "rectangle",
          x = 348,
          y = 206,
          width = 24,
          height = 48,
          rotation = 0,
          gid = 173,
          visible = true,
          properties = {
            ["chara"] = "asr"
          }
        },
        {
          id = 4,
          name = "puppet",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 250,
          width = 36,
          height = 58,
          rotation = 0,
          gid = 179,
          visible = true,
          properties = {
            ["chara"] = "tor"
          }
        },
        {
          id = 5,
          name = "puppet",
          type = "",
          shape = "rectangle",
          x = 470,
          y = 222,
          width = 30,
          height = 66,
          rotation = 0,
          gid = 172,
          visible = true,
          properties = {
            ["chara"] = "asg",
            ["holyshitgasterheightvalue"] = "noway"
          }
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 220,
          y = 306,
          width = 40,
          height = 42,
          rotation = 0,
          gid = 181,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 382,
          y = 306,
          width = 40,
          height = 42,
          rotation = 0,
          gid = 2147483829,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 300,
          y = 312,
          width = 40,
          height = 42,
          rotation = 0,
          gid = 2147483829,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 130,
          width = 78,
          height = 130,
          rotation = 0,
          gid = 175,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          type = "",
          shape = "rectangle",
          x = 104,
          y = 148,
          width = 78,
          height = 148,
          rotation = 0,
          gid = 176,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = 349,
          y = 128,
          width = 78,
          height = 130,
          rotation = 0,
          gid = 2147483823,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 234.5,
          width = 34,
          height = 17.5,
          rotation = 0,
          visible = true,
          properties = {
            ["text"] = "* It's a puppet of your mother."
          }
        },
        {
          id = 53,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 471,
          y = 210.5,
          width = 27,
          height = 14,
          rotation = 0,
          visible = true,
          properties = {
            ["text"] = "* It's a puppet of your father."
          }
        },
        {
          id = 54,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 268,
          y = 200,
          width = 25.5,
          height = 11.5,
          rotation = 0,
          visible = true,
          properties = {
            ["text"] = "* It's...[wait:5]\n* You."
          }
        },
        {
          id = 56,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 347,
          y = 197.5,
          width = 26.5,
          height = 10.5,
          rotation = 0,
          visible = true,
          properties = {
            ["text1"] = "* It's a puppet of...",
            ["text2"] = "* Your throat tightens for a moment."
          }
        },
        {
          id = 61,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 440,
          width = 240,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["exit_sound"] = "doorclose",
            ["map"] = "rng_door",
            ["marker"] = "door",
            ["sound"] = "dooropen"
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "objects_aboveparty",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 13,
          name = "",
          type = "",
          shape = "rectangle",
          x = 302,
          y = 114,
          width = 78,
          height = 148,
          rotation = 0,
          gid = 2147483824,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "",
          shape = "rectangle",
          x = 462,
          y = 146,
          width = 78,
          height = 146,
          rotation = 0,
          gid = 177,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 7,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 19,
          name = "",
          type = "",
          shape = "rectangle",
          x = 110,
          y = 160,
          width = 0,
          height = 240,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 110,
          y = 374,
          width = 160,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 270,
          y = 374,
          width = 0,
          height = 120,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360.667,
          y = 374,
          width = 0,
          height = 120,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 361.667,
          y = 374,
          width = 175,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "",
          shape = "rectangle",
          x = 536.333,
          y = 161.333,
          width = 0,
          height = 240,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 168,
          width = 440,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "",
          type = "",
          shape = "rectangle",
          x = 220.667,
          y = 290,
          width = 37.3333,
          height = 14,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "",
          type = "",
          shape = "rectangle",
          x = 382.667,
          y = 289.958,
          width = 37.3333,
          height = 14.0417,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "",
          type = "",
          shape = "rectangle",
          x = 302,
          y = 295.667,
          width = 36,
          height = 13.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "",
          type = "",
          shape = "rectangle",
          x = 225.333,
          y = 224.667,
          width = 190.667,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "",
          type = "",
          shape = "rectangle",
          x = 225,
          y = 207.5,
          width = 191,
          height = 16.5,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 8,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 50,
          name = "spawn",
          type = "",
          shape = "point",
          x = 314,
          y = 422,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "imagelayer",
      image = "../../../assets/sprites/filters/puppet_room.png",
      id = 6,
      name = "overlay",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 80,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = false,
      repeaty = false,
      properties = {}
    }
  }
}
