return {
  version = "1.11",
  luaversion = "5.1",
  tiledversion = "1.11.0",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 23,
  height = 53,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 11,
  nextobjectid = 368,
  properties = {
    ["music"] = "mirror_room"
  },
  tilesets = {
    {
      name = "mirror",
      firstgid = 1,
      filename = "../tilesets/mirror.tsx"
    },
    {
      name = "wilters_room",
      firstgid = 28,
      filename = "../tilesets/wilters_room.tsx"
    },
    {
      name = "mirror2",
      firstgid = 168,
      filename = "../tilesets/mirror2.tsx",
      exportfilename = "../tilesets/mirror2.lua"
    },
    {
      name = "funhouse_objects",
      firstgid = 170,
      filename = "../tilesets/funhouse_objects.tsx",
      exportfilename = "../tilesets/funhouse_objects.lua"
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 23,
      height = 53,
      id = 1,
      name = "Tile Layer 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 122, 123, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 132, 133, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 142, 143, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 152, 153, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 162, 163, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 14, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 14, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 14, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 14, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 14, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 14, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 14, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 14, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 14, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 14, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 14, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 14, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 14, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 14, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 14, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 14, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 14, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 14, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 14, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 14, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 14, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 14, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 14, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 14, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 14, 16, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7,
        0, 0, 0, 0, 0, 0, 0, 14, 16, 23, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 25,
        0, 0, 0, 0, 0, 0, 0, 14, 17, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7,
        0, 0, 0, 0, 0, 0, 0, 14, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 16,
        0, 0, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 14, 16,
        0, 0, 23, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 25, 14, 16,
        0, 0, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 18, 16,
        0, 0, 14, 8, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 25,
        0, 0, 14, 16, 5, 6, 6, 6, 6, 6, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 14, 16, 23, 24, 24, 24, 24, 24, 25, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 14, 17, 6, 6, 6, 6, 6, 6, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 14, 15, 15, 15, 15, 15, 15, 15, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 14, 15, 15, 15, 15, 15, 15, 15, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 23, 24, 24, 24, 24, 24, 9, 15, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 14, 15, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 1840,
          width = 480,
          height = 280,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 2080,
          width = 240,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 1680,
          width = 40,
          height = 400,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 920,
          y = 1520,
          width = 40,
          height = 360,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 360,
          width = 560,
          height = 1240,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 360,
          width = 240,
          height = 1320,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 0,
          width = 80,
          height = 360,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = -40,
          width = 880,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          type = "",
          shape = "rectangle",
          x = 520,
          y = 0,
          width = 400,
          height = 360,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 1840,
          width = 280,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 233,
          name = "",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 0,
          width = 80,
          height = 120,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 234,
          name = "",
          type = "",
          shape = "polygon",
          x = 280,
          y = 120,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -84.5786, y = 79.673 },
            { x = -159.957, y = 100.059 },
            { x = -160, y = -120 },
            { x = 0, y = -120 }
          },
          properties = {}
        },
        {
          id = 235,
          name = "",
          type = "",
          shape = "polygon",
          x = 360,
          y = 120,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 84.5786, y = 79.673 },
            { x = 159.957, y = 100.059 },
            { x = 160, y = -120 },
            { x = 0, y = -120 }
          },
          properties = {}
        },
        {
          id = 238,
          name = "",
          type = "",
          shape = "rectangle",
          x = 457.065,
          y = 313.986,
          width = 49.428,
          height = 35.7765,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 251,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 1680,
          width = 760,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 239,
          name = "entry",
          type = "",
          shape = "point",
          x = 380,
          y = 2080,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 240,
          name = "spawn",
          type = "",
          shape = "point",
          x = 320,
          y = 640,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 248,
          name = "wilt_pan",
          type = "",
          shape = "point",
          x = 320,
          y = 200,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 367,
          name = "kris_1",
          type = "",
          shape = "point",
          x = 320,
          y = 320,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 8,
      name = "objects_bottom",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 316,
          name = "mirror",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 1840,
          width = 278,
          height = 90,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 317,
          name = "mirror",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 1520,
          width = 558,
          height = 90,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 318,
          name = "mirror",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 1680,
          width = 760,
          height = 90,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 10,
      name = "objects_bottom",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 325,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 1600,
          width = 40,
          height = 80,
          rotation = 0,
          gid = 196,
          visible = true,
          properties = {}
        },
        {
          id = 326,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 1600,
          width = 40,
          height = 80,
          rotation = 0,
          gid = 196,
          visible = true,
          properties = {}
        },
        {
          id = 327,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 1600,
          width = 40,
          height = 80,
          rotation = 0,
          gid = 196,
          visible = true,
          properties = {}
        },
        {
          id = 328,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 1600,
          width = 40,
          height = 80,
          rotation = 0,
          gid = 196,
          visible = true,
          properties = {}
        },
        {
          id = 329,
          name = "",
          type = "",
          shape = "rectangle",
          x = 520,
          y = 1600,
          width = 40,
          height = 80,
          rotation = 0,
          gid = 196,
          visible = true,
          properties = {}
        },
        {
          id = 330,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 1600,
          width = 40,
          height = 80,
          rotation = 0,
          gid = 196,
          visible = true,
          properties = {}
        },
        {
          id = 331,
          name = "",
          type = "",
          shape = "rectangle",
          x = 600,
          y = 1600,
          width = 40,
          height = 80,
          rotation = 0,
          gid = 196,
          visible = true,
          properties = {}
        },
        {
          id = 332,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 1600,
          width = 40,
          height = 80,
          rotation = 0,
          gid = 196,
          visible = true,
          properties = {}
        },
        {
          id = 333,
          name = "",
          type = "",
          shape = "rectangle",
          x = 680,
          y = 1600,
          width = 40,
          height = 80,
          rotation = 0,
          gid = 196,
          visible = true,
          properties = {}
        },
        {
          id = 334,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 1600,
          width = 40,
          height = 80,
          rotation = 0,
          gid = 196,
          visible = true,
          properties = {}
        },
        {
          id = 335,
          name = "",
          type = "",
          shape = "rectangle",
          x = 760,
          y = 1600,
          width = 40,
          height = 80,
          rotation = 0,
          gid = 196,
          visible = true,
          properties = {}
        },
        {
          id = 336,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 1600,
          width = 40,
          height = 80,
          rotation = 0,
          gid = 196,
          visible = true,
          properties = {}
        },
        {
          id = 337,
          name = "",
          type = "",
          shape = "rectangle",
          x = 840,
          y = 1600,
          width = 40,
          height = 80,
          rotation = 0,
          gid = 196,
          visible = true,
          properties = {}
        },
        {
          id = 338,
          name = "",
          type = "",
          shape = "rectangle",
          x = 880,
          y = 1600,
          width = 40,
          height = 80,
          rotation = 0,
          gid = 196,
          visible = true,
          properties = {}
        },
        {
          id = 339,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 1760,
          width = 40,
          height = 80,
          rotation = 0,
          gid = 196,
          visible = true,
          properties = {}
        },
        {
          id = 340,
          name = "",
          type = "",
          shape = "rectangle",
          x = 760,
          y = 1760,
          width = 40,
          height = 80,
          rotation = 0,
          gid = 196,
          visible = true,
          properties = {}
        },
        {
          id = 341,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 1760,
          width = 40,
          height = 80,
          rotation = 0,
          gid = 196,
          visible = true,
          properties = {}
        },
        {
          id = 342,
          name = "",
          type = "",
          shape = "rectangle",
          x = 680,
          y = 1760,
          width = 40,
          height = 80,
          rotation = 0,
          gid = 196,
          visible = true,
          properties = {}
        },
        {
          id = 343,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 1760,
          width = 40,
          height = 80,
          rotation = 0,
          gid = 196,
          visible = true,
          properties = {}
        },
        {
          id = 344,
          name = "",
          type = "",
          shape = "rectangle",
          x = 600,
          y = 1760,
          width = 40,
          height = 80,
          rotation = 0,
          gid = 196,
          visible = true,
          properties = {}
        },
        {
          id = 345,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 1760,
          width = 40,
          height = 80,
          rotation = 0,
          gid = 196,
          visible = true,
          properties = {}
        },
        {
          id = 346,
          name = "",
          type = "",
          shape = "rectangle",
          x = 520,
          y = 1760,
          width = 40,
          height = 80,
          rotation = 0,
          gid = 196,
          visible = true,
          properties = {}
        },
        {
          id = 347,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 1760,
          width = 40,
          height = 80,
          rotation = 0,
          gid = 196,
          visible = true,
          properties = {}
        },
        {
          id = 348,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 1760,
          width = 40,
          height = 80,
          rotation = 0,
          gid = 196,
          visible = true,
          properties = {}
        },
        {
          id = 349,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 1760,
          width = 40,
          height = 80,
          rotation = 0,
          gid = 196,
          visible = true,
          properties = {}
        },
        {
          id = 350,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 1760,
          width = 40,
          height = 80,
          rotation = 0,
          gid = 196,
          visible = true,
          properties = {}
        },
        {
          id = 351,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 1760,
          width = 40,
          height = 80,
          rotation = 0,
          gid = 196,
          visible = true,
          properties = {}
        },
        {
          id = 352,
          name = "",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 1760,
          width = 40,
          height = 80,
          rotation = 0,
          gid = 196,
          visible = true,
          properties = {}
        },
        {
          id = 353,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 1760,
          width = 40,
          height = 80,
          rotation = 0,
          gid = 196,
          visible = true,
          properties = {}
        },
        {
          id = 354,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 1760,
          width = 40,
          height = 80,
          rotation = 0,
          gid = 196,
          visible = true,
          properties = {}
        },
        {
          id = 355,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 1760,
          width = 40,
          height = 80,
          rotation = 0,
          gid = 196,
          visible = true,
          properties = {}
        },
        {
          id = 356,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 1760,
          width = 40,
          height = 80,
          rotation = 0,
          gid = 196,
          visible = true,
          properties = {}
        },
        {
          id = 357,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 1760,
          width = 40,
          height = 80,
          rotation = 0,
          gid = 196,
          visible = true,
          properties = {}
        },
        {
          id = 358,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 1920,
          width = 40,
          height = 80,
          rotation = 0,
          gid = 196,
          visible = true,
          properties = {}
        },
        {
          id = 359,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 1920,
          width = 40,
          height = 80,
          rotation = 0,
          gid = 196,
          visible = true,
          properties = {}
        },
        {
          id = 360,
          name = "",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 1920,
          width = 40,
          height = 80,
          rotation = 0,
          gid = 196,
          visible = true,
          properties = {}
        },
        {
          id = 361,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 1920,
          width = 40,
          height = 80,
          rotation = 0,
          gid = 196,
          visible = true,
          properties = {}
        },
        {
          id = 362,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 1920,
          width = 40,
          height = 80,
          rotation = 0,
          gid = 196,
          visible = true,
          properties = {}
        },
        {
          id = 363,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 1920,
          width = 40,
          height = 80,
          rotation = 0,
          gid = 196,
          visible = true,
          properties = {}
        },
        {
          id = 364,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 1920,
          width = 40,
          height = 80,
          rotation = 0,
          gid = 196,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "objects_party",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 243,
          name = "script",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 600,
          width = 80,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["cutscene"] = "generic.save"
          }
        },
        {
          id = 246,
          name = "script",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 440,
          width = 80,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["cutscene"] = "chase.transform",
            ["once"] = false
          }
        },
        {
          id = 250,
          name = "npc",
          type = "",
          shape = "point",
          x = 320,
          y = 160,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["actor"] = "wilter"
          }
        },
        {
          id = 257,
          name = "script",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 1600,
          width = 40,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {
            ["cutscene"] = "generic.pre_transform_3"
          }
        },
        {
          id = 258,
          name = "script",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 1560,
          width = 80,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["cutscene"] = "generic.pre_transform_4"
          }
        },
        {
          id = 259,
          name = "script",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 1000,
          width = 80,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["cutscene"] = "generic.pre_transform_5"
          }
        },
        {
          id = 260,
          name = "script",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 1760,
          width = 40,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {
            ["cutscene"] = "generic.pre_transform_1"
          }
        },
        {
          id = 261,
          name = "script",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 1760,
          width = 40,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {
            ["cutscene"] = "generic.pre_transform_2"
          }
        },
        {
          id = 365,
          name = "script",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 1883.41,
          width = 83.0948,
          height = 37.2696,
          rotation = 0,
          visible = true,
          properties = {
            ["cutscene"] = "generic.pre_transform"
          }
        },
        {
          id = 366,
          name = "script",
          type = "",
          shape = "rectangle",
          x = 303.965,
          y = 2120,
          width = 146.234,
          height = 37.2696,
          rotation = 0,
          visible = true,
          properties = {
            ["cutscene"] = "generic.cantleave_2",
            ["once"] = false
          }
        }
      }
    }
  }
}
